name: Deploy React CSR
on:
  push:
    branches:
      - main
      - features/** #ทุก branch ของ features จะทำงาน
    #   - "!features/authen"  #ถ้ามี ! จะไม่ทำงาน
  workflow_dispatch:
  pull_request:
    types:
      # event เกิด workflow จะดูว่าเป็น opened ไหม ถ้าเป็น opened จะทํางาน
      - opened
# env:
#   NPM_VERSION: "10.9.2"
jobs:
  build:
    #   lint:
    # environment: developmentClound
    runs-on: ubuntu-latest
    # ถ้าใส่ container  step จะรันใน container เลย
    container: 
      image: oven/bun:1
      env:
        # POSTGRES_PASSWORD: postgres
        NODE_ENV: development
    steps:
      - name: Use env variable
        run: echo "npm version:{{ $NPM_VERSION}}"
      - name: Use repo variable
        run: echo "test URL:{{ vars.TEST_URL}}"

      - name: Clone repo
        uses: actions/checkout@v5
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencie
        run: npm i
      #   - name: Lint
      #     run: npm run lint
      - name: Build
        run: npm run build
      - name: List dist/
        run: ls -l dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

      # บังคับให้ออก เพื่อให้ build fail
      # - name: Forece fail
      #   run: exit 1

  deploy:
    # ทำงานเมื่อ branchrefs/heads/main
    # if: ${{ github.ref == 'refs/heads/main' }}

    # ทำงานเมื่อ job ข้างบนสำเร็จ ให้ไปทำ notifyต่อ     # check ใน  needs ทั้งหมด ว่า success ไหม ถ้าผ่านทั้งหมด
    if: ${{ success() }}

    # needs:
    #   - lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      #   - name: Clone repo
      #     uses: actions/checkout@v5
      #   - name: Install dependencies
      #     run: npm i
      #   - name: Builds
      #     run: npm run build
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist/
      - name: List all files/
        run: ls dist
      - name: Deploy
        run: echo "Deployedssss.."

        #ถ้าต้องการให้โชว์ noti ทั้ง fail  และsuccess ให้ทำ notify 2 อัน
  # notify:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #     - deploy
  #     # check ใน  needs ทั้งหมด ว่า fail ไหม ถ้ามีfail จะทำงาน(มี1อันก็ทำงาน)
  #   # if: failure()
  #   # check ทั้งหมด
  #   if: always()
  #   steps:
  #     - name: Notify Discord noti
  #       env:
  #         DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
  #       uses: Ilshidur/action-discord@master
  #       with:
  #         args: "build  ${{github.sha}} by meee"

  notify-fail:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: failure()
    steps:
      - name: Notify Discord noti
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: "build พัง ไปแก้ใหม่ ${{github.sha}} by meee"

  notify-success:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: success()
    steps:
      - name: Notify Discord noti
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: "build ผ่านแล้ววววววว ${{github.sha}} by ${{github.actor}} "
