name: Matrix
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21, 22, 23]
        browsers: ["firefox", "chrome", "safari", "edge"]
        # ถ้าเจอข้อมูล exclude ไม่ต้องทำงาน
        exclude:
          - node-version: 22
            browsers: "firefox"
        include:
          - node-version: 22
            browsers: "chrome"
          - node-version: 23
            browsers: "safari"
    steps:
      - name: use Node version and test browser
        run: |
          echo "Node version: ${{ matrix.node-version }}"
          echo "Browser: ${{ matrix.browsers }}"
